from pathlib import Path
from jinja2 import Template

DEFAULT_TEMPLATE = """
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans TC", sans-serif;
            line-height: 1.8;
            color: #333;
            background: #f5f5f5;
            padding: 20px;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }
        .header h1 { font-size: 1.8rem; margin-bottom: 10px; }
        .header .meta { font-size: 0.9rem; opacity: 0.9; }
        .header .meta-item { margin: 0 8px; }
        .market-summary {
            background: #e3f2fd;
            padding: 20px;
            border-left: 4px solid #2196f3;
            margin: 20px;
        }
        .market-summary h3 { color: #1976d2; margin-bottom: 10px; }
        .article {
            padding: 20px;
            border-bottom: 1px solid #eee;
        }
        .article:last-child { border-bottom: none; }
        .article h2 {
            color: #333;
            font-size: 1.4rem;
            margin-bottom: 10px;
        }
        .article .meta {
            color: #666;
            font-size: 0.85rem;
            margin-bottom: 15px;
        }
        .article .meta a { color: #2196f3; text-decoration: none; }
        .article .meta a:hover { text-decoration: underline; }
        .section { margin: 15px 0; }
        .section h3 { color: #555; font-size: 1.1rem; margin-bottom: 8px; }
        .section-content { padding-left: 15px; color: #444; }
        .comment {
            background: #fff3e0;
            padding: 15px;
            border-radius: 4px;
            margin-top: 15px;
            border-left: 3px solid #ff9800;
        }
        .comment h3 { color: #e65100; }
        .footer {
            text-align: center;
            padding: 20px;
            color: #999;
            font-size: 0.85rem;
            border-top: 1px solid #eee;
        }
        @media (max-width: 600px) {
            body { padding: 10px; }
            .header { padding: 20px; }
            .header h1 { font-size: 1.4rem; }
            .article { padding: 15px; }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{{ title }}</h1>
            <div class="meta">
                <span class="meta-item">AI 模型: {{ ai_model }}</span>
                <span class="meta-item">主機: {{ hostname }}</span>
                <span class="meta-item">生成時間: {{ html_gen_time }}</span>
                <span class="meta-item">現在時間: <span id="current-time">{{ now_time }}</span></span>
            </div>
        </div>

        {% if market_summary_html %}
        <div class="market-summary">
            <h3>📊 本日市場總評</h3>
            <div class="section-content">{{ market_summary_html }}</div>
        </div>
        {% endif %}

        {% for article in articles %}
        <article class="article">
            <h2>{{ article.title }}</h2>
            <div class="meta">
                📅 {{ article.date }} | 📰 來源: <a href="{{ article.url }}" target="_blank">{{ article.source }}</a>
            </div>
            <div class="section">
                <h3>📝 內容</h3>
                <div class="section-content">{{ article.content_html }}</div>
            </div>
            {% if article.comment_html %}
            <div class="comment">
                <h3>💡 專業評論</h3>
                <div class="section-content">{{ article.comment_html }}</div>
            </div>
            {% endif %}
        </article>
        {% endfor %}

        <div class="footer">
            <p>AI News 分析系統 | 主機: {{ hostname }} | 文章時間: {{ article_gen_time }}</p>
            <p>&copy; {{ current_year }} Generated by AI News Analysis System</p>
        </div>
    </div>
    <script>
    function updateTime() {
        const now = new Date();
        const year = now.getFullYear();
        const month = String(now.getMonth() + 1).padStart(2, '0');
        const day = String(now.getDate()).padStart(2, '0');
        const hours = String(now.getHours()).padStart(2, '0');
        const minutes = String(now.getMinutes()).padStart(2, '0');
        const seconds = String(now.getSeconds()).padStart(2, '0');
        const timeString = `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
        document.getElementById('current-time').textContent = timeString;
    }
    updateTime();
    setInterval(updateTime, 1000);
    </script>
</body>
</html>
"""

template_path = Path(__file__).parent / "template.html"
template_path.parent.mkdir(parents=True, exist_ok=True)

if not template_path.exists():
    template_path.write_text(DEFAULT_TEMPLATE, encoding="utf-8")
